services:
  - type: web
    name: doctalk-backend
    runtime: python
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn doctalk.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false # Get this from Supabase and set in dashboard
      - key: GOOGLE_API_KEY
        sync: false # Set in dashboard
      - key: CORS_ALLOWED_ORIGINS
        value: "https://doctalk-frontend.onrender.com" # Will need to be updated manualy or use * for initial test

staticSites:
  - name: doctalk-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishDir: "dist"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: doctalk-backend
          property: url
